interfaces:
  - name: lo0.0
    description: Loopback interface
    ip: 12.12.12.12
    peer: 192.168.2.2
    mask: 32
  # - name: ge-0/0/0.0
  #   description: Zero interface
  #   ip: 10.0.4.1
  #   peer: 192.168.1.2
  #   mask: 30
  - name: ge-0/0/1.0
    description: First interface
    ip: 10.0.8.14
    peer: 192.168.2.2
    mask: 30
  # - name: ge-0/0/2.0
  #   description: Second interface
  #   ip: 192.168.2.2
  #   peer: 192.168.2.2
  #   mask: 30
  - name: ge-0/0/3.0
    description: Third interface
    ip: 10.0.8.2
    peer: 192.168.2.2
    mask: 30
  # - name: ge-0/0/4.0
  #   description: Fourth interface
  #   ip: 10.
  #   peer: 192.168.2.2
  #   mask: 30