interfaces:
  - name: lo0.0
    description: Loopback interface
    ip: 1.1.1.1
    peer: 192.168.2.2
    mask: 32
  - name: ge-0/0/0.0
    description: Zero interface
    ip: 172.30.0.1
    peer: 192.168.1.2
    mask: 30
  - name: ge-0/0/1.0
    description: First interface
    ip: 10.0.4.17
    peer: 192.168.2.2
    mask: 30
  - name: ge-0/0/2.0
    description: Second interface
    ip: 172.30.0.9
    peer: 192.168.2.2
    mask: 30
  # - name: ge-0/0/3.0
  #   description: Third interface
  #   ip: 10.0.5.1
  #   peer: 192.168.2.2
  #   mask: 24
  - name: ge-0/0/4.0
    description: Third interface
    ip: 172.30.0.5
    peer: 192.168.2.2
    mask: 30
  # - name: ge-0/0/4.0
  #   description: Fourth interface
  #   ip: 10.
  #   peer: 192.168.2.2
  #   mask: 30