interfaces:
  - name: lo0.0
    description: Loopback interface
    ip: 2.2.2.2
    peer: 192.168.2.2
    mask: 32
  # - name: ge-0/0/0.0
  #   description: Zero interface
  #   ip: 10.0.4.1
  #   peer: 192.168.1.2
  #   mask: 30
  # - name: ge-0/0/1.0
  #   description: First interface
  #   ip: 10.0.4.9
  #   peer: 192.168.2.2
  #   mask: 30
  - name: ge-0/0/2.0
    description: First interface
    ip: 172.30.0.13
    peer: 192.168.2.2
    mask: 30
  - name: ge-0/0/3.0
    description: Third interface
    ip: 172.30.0.17
    peer: 192.168.2.2
    mask: 30
  # - name: ge-0/0/4.0
  #   description: Fourth interface
  #   ip: 10.0.5.2
  #   peer: 192.168.2.2
  #   mask: 24
  - name: ge-0/0/5.0
    description: Fourth interface
    ip: 172.30.0.2
    peer: 192.168.2.2
    mask: 24